/*
	midi2gmn Library
	Copyright (C) 1992 - 2012 Juergen F. Kilian


	This library is free software; you can redistribute it and/or
	modify it under the terms of the GNU Lesser General Public
	License as published by the Free Software Foundation; either
	version 3 of the License, or (at your option) any later version.

	This library is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
	Lesser General Public License for more details.

	You should have received a copy of the GNU Lesser General Public
	License along with this library; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kitcon_midi2gmn_Midi2Gmn */

#ifndef _Included_org_kitcon_midi2gmn_Midi2Gmn
#define _Included_org_kitcon_midi2gmn_Midi2Gmn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kitcon_midi2gmn_Midi2Gmn
 * Method:    process
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kitcon_midi2gmn_Midi2Gmn_process
  (JNIEnv *, jclass,  jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
